### ISSUE TITLE
out of bonds with brascii code map in lx-300

### ISSUE THREAD

**Issue by eduardogross** [bertronika/copris#1]
Thank you very much for your work. Bold, underline and italic are working well with markdown text. I am using debian 11 with lx-300 connected at parallel port.

But I could not make the translation with characters.

Error messages received after running copris with -t brasil.ini argument

Value '192' in '192' is out of bounds.
Failure while processing value for `�'.
Value '224' in '224' is out of bounds.
Failure while processing value for `�'.
Value '193' in '193' is out of bounds.
Failure while processing value for `�'.
Value '225' in '225' is out of bounds.
Failure while processing value for `�'.
Value '194' in '194' is out of bounds.
Failure while processing value for `�'.
Value '226' in '226' is out of bounds.
Failure while processing value for `�'.
Value '195' in '195' is out of bounds.
Failure while processing value for `�'.
Value '227' in '227' is out of bounds.
Failure while processing value for `�'.
Value '199' in '199' is out of bounds.
Failure while processing value for `�'.

brasil.ini content, based on brascii page <https://pt.wikipedia.org/wiki/BRASCII>, with epson lx-300 character map configured as brascii:
À = 192
à = 224
Á = 193
á = 225
Â = 194
â = 226
Ã = 195
ã = 227
Ç = 199
ç = 231
É = 201
é = 233
Ê = 202
ê = 234
È = 200
è = 232
Í = 205
í = 237
Ó = 211
ó = 243
Ô = 212
ô = 244
Õ = 213
Õ = 245
Ú = 218
ú = 250
Ü = 220
ü = 252
Ñ = 209
ñ = 241
º = 186
ª = 170
§ = 167
ä = 228
Ä = 196
ö = 246
Ö = 214
ß = 223

I tried with hexadecimal values too and recieved the same "out of bonds" massage.

I also tried another  translation table, using only the first 126 ascii characters,  that way:
á = 97
à = 97
ä = 97
ã = 97
â = 97
é = 101
è = 101 and so on.
This way I did not receive any error messages, but the characters were also not translated. They were printed so:
á was printed Ã¡
é was printed Ã©
ó was printed Ã³
This was the same result I had without using any translation table.

I would appreciate to know what I am doing wrong and if there is any limitation using characters above 126.

**Comment by bertronika** [comment]
It appears you've hit an unintended limitation. Currently, the parser only works with numbers up to 127 (the maximum of a signed char), which is obviously unwanted.

I'll amend the problem, time permitting. I'll update this issue for you to test it.

**Comment by eduardogross** [comment]
I thank you very much for your attention.It is a long time since I am searching for a good way to print with dot matrix native characters in linux. I found few people interested in it, but, like me, these do not seem to know about programming. What I currently do:I write text with libreoffice; convert them to "rtf for old applications" using abiword; open these rtf files with wordperfect 6 for dos using dosemu; eventually, if needed, I manually delete remaining font codes.Your idea to print markdown files in a dot matrix is great.Greatings from BrazilEduardo Gross ──────────────────────────────────────────────────────────────────De: "Nejc Bertoncelj" Enviada: 2023/03/12 17:53:51Para: ***@***.***:  ***@***.***, ***@***.***:  Re: [bertronika/copris] out of bonds with brascii code map in lx-300 (Issue #1)It appears you've hit an unintended limitation. Currently, the parser only works with numbers up to 127 (the maximum of a signed char), which is obviously unwanted.I'll amend the problem, time permitting. I'll update this issue for you to test it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/bertronika/copris/issues/1#issuecomment-1465296961","url": "https://github.com/bertronika/copris/issues/1#issuecomment-1465296961","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by bertronika** [comment]
I've patched the offending problem, hopefully fixing this issue. GitHub closed it automatically, but I'll still wait for your reply. I've also added the BraSCII character set, you'll find it in `encodings/brascii.ini`.

**Comment by eduardogross** [comment]
It worked well! Thank you very much, your work is very usefull!

**Comment by eduardogross** [comment]
If it could be useful for anyone, I put here the ESC/P commands I use in order to format the printed page from linux terminal, before sending the text to print throu copris:
echo -e '\x1B\x40' > /dev/lp0 #inicialize printer
echo -e '\x1B\x32' > /dev/lp0 #line space 1/6'
echo -e '\x1B\x50' > /dev/lp0 #10 cpi character size
echo -e '\x1B\x6C\x0B' > /dev/lp0 # left margin, 10 caracteres, 3 cm
echo -e '\x1B\x51\x4A' > /dev/lp0 #right margin, 75 caracteres, 2 cm
echo -e '\x1B\x61\x3' > /dev/lp0 #justify
echo -e '\x0D' > /dev/lp0 #CR
echo -e '\x0A' > /dev/lp0 #LF
